src/Cnes/PhileaBundle/Entity/Projet.php
<?php

namespace Cnes\PhileaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Projet
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Cnes\PhileaBundle\Entity\ProjetRepository")
 */
class Projet
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Domaine")
     * @ORM\JoinColumn(nullable=true, name="idDomaine", referencedColumnName="id")
     */
    protected $domaine;

    /**
     * @ORM\ManyToOne(targetEntity="Etablissement")
     * @ORM\JoinColumn(nullable=true, name="idEtablissement", referencedColumnName="id")
     */
    protected $etablissement;

    /**
     * @ORM\ManyToOne(targetEntity="Classe")
     * @ORM\JoinColumn(nullable=true, name="idClasse", referencedColumnName="id")
     */
    protected $classe;
    
    /**
    * @ORM\OneToMany(targetEntity="Cnes\PhileaBundle\Entity\Etape", mappedBy="projet")
    */
    private $etapes;

    /**
     * @ORM\ManyToMany(targetEntity="Cnes\PhileaBundle\Entity\User", mappedBy="projets")
     **/
    private $users;


    public function __construct() {
        $this->etapes = new \Doctrine\Common\Collections\ArrayCollection();
        $this->users = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set domaine
     *
     * @param \Cnes\PhileaBundle\Entity\Domaine $domaine
     * @return Projet
     */
    public function setDomaine(\Cnes\PhileaBundle\Entity\Domaine $domaine = null)
    {
        $this->domaine = $domaine;
    
        return $this;
    }

    /**
     * Get domaine
     *
     * @return \Cnes\PhileaBundle\Entity\Domaine 
     */
    public function getDomaine()
    {
        return $this->domaine;
    }

    /**
     * Set etablissement
     *
     * @param \Cnes\PhileaBundle\Entity\Etablissement $etablissement
     * @return Projet
     */
    public function setEtablissement(\Cnes\PhileaBundle\Entity\Etablissement $etablissement = null)
    {
        $this->etablissement = $etablissement;
    
        return $this;
    }

    /**
     * Get etablissement
     *
     * @return \Cnes\PhileaBundle\Entity\Etablissement 
     */
    public function getEtablissement()
    {
        return $this->etablissement;
    }

    /**
     * Set classe
     *
     * @param \Cnes\PhileaBundle\Entity\Classe $classe
     * @return Projet
     */
    public function setClasse(\Cnes\PhileaBundle\Entity\Classe $classe = null)
    {
        $this->classe = $classe;
    
        return $this;
    }

    /**
     * Get classe
     *
     * @return \Cnes\PhileaBundle\Entity\Classe 
     */
    public function getClasse()
    {
        return $this->classe;
    }

    /**
     * Add etapes
     *
     * @param \Cnes\PhileaBundle\Entity\Etape $etapes
     * @return Projet
     */
    public function addEtape(\Cnes\PhileaBundle\Entity\Etape $etapes)
    {
        $this->etapes[] = $etapes;
    
        return $this;
    }

    /**
     * Remove etapes
     *
     * @param \Cnes\PhileaBundle\Entity\Etape $etapes
     */
    public function removeEtape(\Cnes\PhileaBundle\Entity\Etape $etapes)
    {
        $this->etapes->removeElement($etapes);
    }

    /**
     * Get etapes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getEtapes()
    {
        return $this->etapes;
    }


    /**
     * Add users
     *
     * @param \Cnes\PhileaBundle\Entity\User $users
     * @return Projet
     */
    public function addUser(\Cnes\PhileaBundle\Entity\User $users)
    {
        $this->users[] = $users;
    
        return $this;
    }

    /**
     * Remove users
     *
     * @param \Cnes\PhileaBundle\Entity\User $users
     */
    public function removeUser(\Cnes\PhileaBundle\Entity\User $users)
    {
        $this->users->removeElement($users);
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getUsers()
    {
        return $this->users;
    }
    
    public function getAvancementMax() {
        $max = 0;
        foreach ($this->getEtapes() as $etape){
            if($etape->getAvancement()>$max && $etape->getEtat() == Etape::VALIDE)
                $max=$etape->getAvancement();
        }
        return $max;
    }
    
    public function getAvancementMaxNonPublie() {
        $max = 0;
        foreach ($this->getEtapes() as $etape){
            if($etape->getAvancement()>$max && ($etape->getEtat() == Etape::VALIDE || $etape->getEtat() == Etape::ATTENTE_VALIDATION) )
                $max=$etape->getAvancement();
        }
        return $max;
    }


    public function getGestionnaires() {
        $gestionnaires = array();
        foreach ($this->getUsers() as $user){
            if($user && $user->getRoles()) {
               $r = $user->getRoles();
               if(in_array("ROLE_GESTIONNAIRE", $r))
                  $gestionnaires[] = $user;
            }
        }

        return $gestionnaires;
    }




}

src/Cnes/PhileaBundle/Controller/DefaultController.php
<?php

namespace Cnes\PhileaBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Cnes\PhileaBundle\Entity\Etape;
use Cnes\PhileaBundle\Entity\User;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller {

    /**
     * @Route("/",name="philea_index")
     * @Template()
     */
    public function indexAction() {
        
         $articles = $this->getDoctrine()->getRepository('PhileaBundle:Article')
                ->findBy(
                array('etat' => 1), array('date' => 'DESC'));

        if (!$articles) {
            throw $this->createNotFoundException('Aucune étape de projet trouvée pour ce projet');
        }
        
        
        return $this->render('PhileaBundle:Default:accueil.html.twig', array('articles' => $articles));
    }

    /**
     * @Route("/synoptique", name="philea_synoptique")
     * @Template()
     */
    public function synoptiqueAction() {
        return $this->render('PhileaBundle:Default:synoptique.html.twig');
    }

    /**
     * @Route("/domaine/{idDomaine}/",name="philea_domaine")
     * @Template()
     */
    public function domaineAction($idDomaine) {
        $domaine = $this->getDoctrine()->getRepository('PhileaBundle:Domaine')
                ->find($idDomaine);

        if (!$domaine) {
            throw $this->createNotFoundException('Aucun domaine trouvé');
        }

        $projets = $this->getDoctrine()->getRepository('PhileaBundle:Domaine')->find($idDomaine)->getProjets();

        return array('domaine' => $domaine, 'projets' => $projets/* , 'etapes' => $etapes */);
    }

    /**
     * @Route("/projet/{idProjet}/", name="philea_projet"))
     * @Template()
     */
    public function projetAction($idProjet) {
        /* $projet = $this->getDoctrine()->getRepository('PhileaBundle:Projet')
          ->find($idProjet); */

        $domaine = $this->getDoctrine()->getRepository('PhileaBundle:Projet')
                        ->find($idProjet)->getDomaine();
        $etapes = $this->getDoctrine()->getRepository('PhileaBundle:Etape')
                ->findBy(
                array('projet' => $idProjet, 'etat' => 1), array('avancement' => 'DESC'));

        if (!$etapes) {
            throw $this->createNotFoundException('Aucune étape de projet trouvée pour ce projet');
        }

        return $this->render('PhileaBundle:Default:etape.html.twig', array('domaine' => $domaine, 'etapes' => $etapes));
    }

    

     /**
     * @Route("/gestion/utilisateurs/",name="philea_utilisateurs")
     * @Template()
     */
    public function usersAction() {
        $userManager = $this->get('fos_user.user_manager');
        $users = $userManager->findUsers();

        return $this->render('PhileaBundle:Default:users.html.twig', array('users' => $users));
    }

    /**
     * @Route("/gestion/utilisateurs/projets/{idUser}",name="philea_utilisateur_projets")
     * @Template()
     */
    public function userProjetsAction($idUser) {

        $projets = $this->getDoctrine()
                        ->getRepository('PhileaBundle:User')
                        ->find($idUser)->getProjets();

        $user = $this->getDoctrine()
                ->getRepository('PhileaBundle:User')
                ->find($idUser);

        return $this->render('PhileaBundle:Default:projetsuser.html.twig', array('projets' => $projets, 'user' => $user));
    }

    /**
     * @Route("/gestion/utilisateurs/projetsuser/delete/{idUser}/{idProjet}",name="philea_utilisateur_projet_retirer")
     * @Template()
     */
    public function userProjetsDeleteAction($idUser, $idProjet) {
        $em = $this->getDoctrine()->getManager();

        $user = $this->getDoctrine()->getRepository('PhileaBundle:User')->find($idUser);
        $projet = $this->getDoctrine()->getRepository('PhileaBundle:Projet')->find($idProjet);
        $user->removeProjet($projet);
        $em->flush();

        return $this->redirect($this->generateUrl('philea_utilisateur_projets', array('idUser' => $idUser)));
    }

    /**
     * @Route("/gestion/utilisateurs/projet/ajout/{idUser}/",name="philea_utilisateur_projet_ajouter")
     * @Template()
     */
    public function userProjetsAjoutAction(Request $request, $idUser) {
        // En cours !!!!
        // TODO présenter les projets non encore associés à l'utilisateur d'id = idUser

        $projets = $this->getDoctrine()
                        ->getRepository('PhileaBundle:Projet')->findAll();

        $userRedacteur = $this->getDoctrine()
                        ->getRepository('PhileaBundle:User')->find($idUser);

        //$projetsGestionnaire = $this->getDoctrine()
        //                ->getRepository('PhileaBundle:User')->find($this->getUser())->getProjets();

        $form = $this->createFormBuilder()
                ->add('projet_id', 'choice', array(
                    'choices' => array('1' => '1', '2' => '2', '3' => '3'
                        , '4' => '4', '5' => '5', '6' => '6'
                        , '7' => '7', '8' => '8', '9' => '9'
                        , '10' => '10', '11' => '11', '12' => '12'
                        , '13' => '13', '14' => '14', '15' => '15'
                        , '16' => '16', '17' => '17', '18' => '18'
                        , '19' => '19', '20' => '20', '21' => '21'
                        , '22' => '22', '23' => '23', '24' => '24'
                        , '25' => '25', '26' => '26', '27' => '27'
                        , '28' => '28', '29' => '29', '30' => '30'
                        , 'required' => true,
            )))
                ->add('Ajouter', 'submit')
                ->getForm();

        if ($request->isMethod('POST')) {
            $form->submit($request);

            if ($form->isValid()) {
                $data = $request->request->all();
                $user_id = $idUser;
                $projet_id = $data['form']['projet_id'];

                $em = $this->getDoctrine()->getManager();
                $user = $this->getDoctrine()->getRepository('PhileaBundle:User')->find($user_id);
                $projet = $this->getDoctrine()->getRepository('PhileaBundle:Projet')->find($projet_id);

                $user->addProjet($projet);
                $em->flush();

                return $this->redirect($this->generateUrl('philea_utilisateur_projets', array('idUser' => $idUser)));
            }
        }

        return $this->render('PhileaBundle:Default:formAddUserProjet.html.twig', array(
                    'form' => $form->createView(), 'idUser' => $idUser, 'projetsGestionnaire' => $projets
        ));
    }

    /**
     * @Route("/projets/", name="philea_projets")
     * @Template()
     */
    public function projetsListAction() {
        $em = $this->getDoctrine()->getManager();
        //Passage de 112 à 67 requêtes,
        $projets = $this->getDoctrine()->getRepository('PhileaBundle:Projet')->getAllProjets(); //getMyAll();//findAll();
        $user = $this->getUser();

        $repo = $this->getDoctrine()->getRepository('PhileaBundle:Projet');

        $gest = array();
        foreach ($projets as $p) :
            $gestionnaires = $repo->getAllGestionnaires($p->getId());
            if (!$gestionnaires)
                $gestionnaires = "(vide)";
            else {
                $res = "";
                foreach ($gestionnaires as $u) :
                    if ($res)
                        $res .=", ";
                    $res .= $u->getUsername();
                endforeach;
                $gestionnaires = $res;
            }
            $gest[$p->getId()] = $gestionnaires;
        endforeach;
        return array('projets' => $projets, 'user' => $user, 'gest' => $gest);
    }

}

src/Cnes/PhileaBundle/Resources/views/Default/accueil.html.twig
{% extends "::layout.html.twig" %}

{% block body %}
<div class="container">

    <div class="row">

        <div class="col-xs-2"> <!-- required for floating -->
            <!-- Nav tabs -->
            <ul class="nav nav-tabs tabs-left">
                <li  class="active"><a href="#news" data-toggle="tab">Actualités</a></li>
                <li><a href="#rosetta" data-toggle="tab">Rosetta</a></li>
                <li><a href="#philea" data-toggle="tab">Philea</a></li>
                <li><a href="#acteurs" data-toggle="tab">Acteurs du projet</a></li>
            </ul>
        </div>

        <div class="col-xs-9">
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane  active" id="news">
                {% for article in articles %}
                    <table width="100%" class="table">
                        <tr>
                            <th colspan="2"><div class="text-center">{{article.titre}}</div><div class="text-right" style="margin-top: -20px;">{{article.date|date("m/d/Y")}}</div></th>
                        </tr>
                        <tr>
                            
                            <td>{{ article.contenu|raw }}</td>
                        </tr>
                    </table>
                    <br /><br />
    {% endfor %}

                </div>
                <div class="tab-pane" id="rosetta">
                    <ul>
                        <li>L'objectif de la mission Rosetta de l'Agence Spatiale Européenne (ESA) est l'étude de la comète Churyumov Gerasimenko avec laquelle la sonde a rendez-vous en Août 2014 pour une période d'observation de 18 mois.<br/>
                            La mission <a href="http://smsc.cnes.fr/ROSETTA/Fr/"> Rosetta </a></li>
                        <li><img src="{{ asset('img/site/rosetta_cometep.gif') }}"/></li>
                    </ul>

                </div>
                <div class="tab-pane" id="philea">
                    <p>Le projet Philea consiste à concevoir puis présenter au grand public une maquette à taille réelle
                        de Philae, l’atterrisseur de la mission Rosetta qui se posera fin 2014
                        sur la comète Churyumov Gerasimenko.</p>
                    <p>La réalisation de cette réplique, baptisée Philea, est attendue pour juin 2014.</p>
                    <p></p>L'intérêt du projet Plilea est multiple :</p>
                    <ul> <li>Pour le public, découvrir des composantes du projet Rosetta</li>
                        <li>Pour l'élève, participer à un véritable projet, en mode collaboratif</li>
                        <li>Pour l'enseignant, offrir à ses élèves un cadre de projet réaliste et collaboratif</li>
                    </ul>
                </div>
                <div class="tab-pane" id="acteurs">
                    <p>22 classes / 11 établissements des académies de Créteil, Paris, Versailles et Limoges</p>
                    <table class="table table-bordered table-responsive table-condensed">
                        <thead> <tr>
                                <th class="text-center">Académie</th>
                                <th class="text-center">Établissement</th>
                                <th class="text-center">Ville</th>
                                <th class="text-center">Classes</th>
                            </tr></thead>
                        <tbody>
                            <tr>
                                <td rowspan="5">Créteil</td>
                                <td>Lycée du Gué à Tresmes</td>
                                <td>Congis (77)</td>
                                <td><ul><li>BAC STD2A</li> <li>BMA GD</li></ul> </td>
                            </tr>
                            <tr>

                                <td>Lycée François Mansart</td>
                                <td>La Varenne (94)</td>
                                <td><ul><li>BTS SCBH</li></ul></td>
                            </tr>
                            <tr>

                                <td>Lycée Léonard de Vinci</td>
                                <td>Melun (77)</td>
                                <td><ul>
                                        <li>BAC PRO TU</li>
                                        <li>BTS CPI</li>
                                        <li>BTS SIO</li>
                                        <li>Licence ISCM</li>
                                    </ul></td>
                            </tr>
                            <tr>

                                <td>Lycée Eugénie Cotton</td>
                                <td>Montrueil (93)</td>
                                <td>
                                    <ul>
                                        <li>BAC STD2A</li>
                                        <li>BTS DE</li>
                                    </ul>
                                </td>
                            </tr>
                            <tr>

                                <td>Lycée Louis Armand</td>
                                <td>Nogent sur marne (94)</td>
                                <td>
                                    <ul>
                                        <li>BTS CPI</li>
                                        <li>BTS ET</li>
                                        <li>BTS IRIS</li>
                                        <li>BTS SE</li>
                                    </ul>
                                </td>
                            </tr>
                            <tr>
                                <td>Limoges</td>
                                <td>Lycée Cabanis</td>
                                <td>Brive-la-gaillarde (19)</td>
                                <td>
                                    <ul>
                                        <li>BTS CPI</li>
                                    </ul>

                                </td>
                            </tr>
                            <tr>
                                <td rowspan="4">Paris</td>
                                <td>Lycée Chenneviere-Malézieux</td>
                                <td>Paris</td>
                                <td>
                                    <ul>
                                        <li>BAC PRO TU</li>
                                    </ul>

                                </td>
                            </tr>
                            <tr>

                                <td>Lycée Diderot</td>
                                <td>Paris</td>
                                <td>
                                    <ul>
                                        <li>BAC STI2D</li>
                                        <li>BTS CIM</li>
                                        <li>BTS IRIS</li>
                                    </ul>
                                </td>
                            </tr>
                            <tr>

                                <td>Lycée Louis Armand</td>
                                <td>Paris</td>
                                <td>
                                    <ul>
                                        <li>BTS CPI</li>
                                    </ul>

                                </td>
                            </tr>
                            <tr>

                                <td>Lycée Dorian</td>
                                <td>Paris</td>
                                <td>
                                    <ul>
                                        <li>BTS IPM</li>
                                        <li>BTS IRIS</li>
                                    </ul>

                                </td>
                            </tr>
                            <tr>
                                <td>Versailles</td>
                                <td>Lycée Alexandre Denis</td>
                                <td>Cerny (91)</td>
                                <td>
                                    <ul>
                                        <li>BAC PRO CTRM</li>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

        <div class="clearfix"></div>

    </div>
</div>

{% endblock %}

src/Cnes/PhileaBundle/Resources/views/Default/ajoutEtape.html.twig
{% extends "::layout.html.twig" %}
{% block title %}Projet Philae{% endblock%}
{% block body %}



    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
       {{ form(form) }}

    {% else %}

        Vous n'êtes pas connecté ! <br />
        <a href="{{ path('fos_user_security_login') }}">Connexion</a>
    {% endif %}


{% endblock %}

src/Cnes/PhileaBundle/Resources/views/Default/domaine.html.twig
{% extends "::layout.html.twig" %}

{% block body %}
<div id="titre">{{domaine.nom}}</div>
    <div class="text-center">
        {{domaine.description | raw}} <br />
        <img src="{{asset(("img/upload/domaine/" ~ domaine.path) |  apply_filter('domaine'))}}" />
</div>
 <br />
    <table class="table"> 
        <tr>
            <td>Discipline</td>
            <td>Etablissement</td>
            <td>Classe</td>
            <td>Académie</td>
            <td>Projet</td>
            <td>Avancement</td>
        </tr>
        
        {% for projet in projets %}
            <tr>
            <td>{{ projet.classe.discipline}}</td>
            <td>{{ projet.etablissement.nom}}</td>
            <td>{{ projet.classe.nomcourt}}</td>
            <td>{{ projet.etablissement.academie}}</td>            
            <td><a href="{{ path('philea_projet',{'idProjet' : projet.id}) }}">Voir les étapes</a></td>
            <td>{{ projet.avancementMax}}%</td>
            </tr>
        {% endfor %}
        
    </table>
{% endblock %}
    

src/Cnes/PhileaBundle/Resources/views/Default/etape.html.twig
    {% extends "::layout.html.twig" %}

{% block body %}
<div class="text-center">
    <span id="titre"><a href="{{ path('philea_domaine',{'idDomaine' : domaine.id}) }}">{{domaine.nom}}</a> - {{domaine.typeDomaine}}</span><br />
        {{domaine.description}}
</div>
<br />

<style>  #progressbar {
        background-color: black;
        border-radius: 13px; /* (height of inner div) / 2 + padding */
        padding: 3px;
        width:50%;
        margin:auto;
        text-align: right;
        line-height:1;
        color:white;
    }

    #progressbar > div {
        background-color: #01B0F0;
        width:{% if etapes[0].avancement is defined %} {{etapes[0].avancement}}%
                     {% else %}  0%
                     {% endif %} ;/* Adjust with JavaScript */
        border-radius: 10px;
        line-height:1;
    }
</style>

<div id="progressbar">

    <div>{% if etapes[0].avancement is defined %}

                {{etapes[0].avancement}}%

        {% else %}
        0%
            {% endif %}</div>

</div>
<br /><br />
    {% for etape in etapes %}
<table width="100%" class="table">
    <tr>
        <th colspan="2"><div class="text-center">{{etape.titre}}</div><div class="text-right" style="margin-top: -20px;">{{etape.avancement}} %</div></th>
</tr>
<tr>
    <td width="10%"><a href="{{ asset("img/upload/" ~ etape.path)}}"  class="example-image-link"  data-lightbox="example-2"><img src='{{ ("img/upload/" ~ etape.path) |  apply_filter('my_thumb')}}'  /></a></td>
    <td width="90%">{{ etape.contenu|raw }}</td>
</tr>
</table>
<br /><br />
    {% endfor %}


{% endblock %}

src/Cnes/PhileaBundle/Resources/views/Default/formAddUserProjet.html.twig
{% extends "::layout.html.twig" %}
{% block title %}Projet Philae{% endblock%}
{% block body %}



    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}

       {{ form_start(form) }}
    {{ form_errors(form) }}
     <div>
         <label for="form_projet_id" class="required">Projet : </label>
        <select id="form_projet_id" name="form[projet_id]">
            {% for projet in projetsGestionnaire %}
                <option value="{{projet.id}}">{{projet.domaine.nom}} - {{projet.etablissement.nom}} - {{projet.classe.nomcourt}}</option>
            {% endfor %}            
        </select>
        </div>
        <!-- Ligne à garder, sinon problème
            {{ form_row(form.projet_id) }}
        -->

{{ form_end(form) }}

    {% else %}

Vous n'êtes pas connecté ! <br />
<a href="{{ path('fos_user_security_login') }}">Connexion</a>
    {% endif %}









{% endblock %}

src/Cnes/PhileaBundle/Resources/views/Default/projetsList.html.twig
{% extends "::layout.html.twig" %}

{% block head %}


<link rel="stylesheet" href="{{ asset('css/demo_table.css') }}" type="text/css"/>
<script type="text/javascript" language="javascript" src="{{ asset('js/jquery.dataTables.js') }}"></script>
<link rel="stylesheet" href="{{ asset('css/philea.css') }}" type="text/css"/>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('#projetslist').dataTable({
            "iDisplayLength": -1,
            "oLanguage": {
                "sEmptyTable": "Aucune donnée correspondante",
                "sLoadingRecords": "Traitement en cours...",
                "sProcessing": "Traitement en cours...",
                "sZeroRecords": "Aucune donnée correspondante",
                "sInfo": "Affichage de _START_ à  _END_ sur _TOTAL_ éléments",
                "sInfoEmpty": "Aucun élément",
                "sInfoFiltered": "",
                "sSearch": "Filtre :",
                "sLengthMenu": 'Affiche <select>' +
                        '<option value="5">5</option>' +
                        '<option value="10">10</option>' +
                        '<option value="15">15</option>' +
                        '<option value="20">20</option>' +
                        '<option value="25">25</option>' +
                        '<option value="-1">Tous</option>' +
                        '</select> projets par page',
                "oPaginate": {
                    "sFirst": "<<",
                    "sLast": ">>",
                    "sNext": ">",
                    "sPrevious": "<"
                }
            },
            "aaSorting": [],
            "sPaginationType": "full_numbers"
        });
    });
</script>
{% endblock %}

{% block body %}
<div class="text-center">
    <span id="titre">Les Projets</span><br />
</div><br />
<p>Cette rubrique
    présente les différents projets dans lesquels les étudiants sont
    engagés. Chaque équipe travaille sur une partie de l'atterrisseur dans
    le cadre de son projet d'études. Chaque projet est constitué d'étapes.
    Vous pouvez voir ici le niveau d'avancement de chacun d'entre eux.    </p>
<table cellpadding="0" cellspacing="0" class="display" id="projetslist"  border="0" width="100%" >
    <thead>
        <tr>
            <th>Type Domaine</th>
            <th>Domaine</th>
            <th>Discipline</th>
            <th>Etablissement</th>
            <th>Classe</th>
            <th>Academie</th>
            <th>Gestionnaire(s)</th>
            <th>Projet</th>
            <th>Avancement</th>
        </tr>
    </thead>
    <tbody>
    {% for projet in projets %}
        <tr>
            <td>{{projet.domaine.typeDomaine}}</td>
            <td>{% set domaine = projet.domaine.id %}
                <a href="{{ path('philea_domaine',{'idDomaine' :  domaine }) }}"> {{projet.domaine.nom}}</a></td>
            <td>{{projet.classe.discipline}}</td>
            <td>{{projet.etablissement.nom}}</td>
            <td>{{projet.classe.nomcourt}}</td>
            <td>{{projet.etablissement.academie}}</td>
            <td> {{gest[projet.id]}}
              {#
              {%  if  projet.gestionnaires %}
                  {% for user in projet.gestionnaires %}
                      {{ user.username }} &nbsp;
                  {% endfor %}
              {% endif %}
              #}
              {#
              {% if user  %}
              <br/> {{user.roles[0]}}
              {% endif %}
              #}
            </td>
            <td><a href="{{ path('philea_projet',{'idProjet' : projet.id}) }}">Voir les étapes</a></td>
            <td>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="{{ projet.avancementMax // 1 }}" aria-valuemin="0" aria-valuemax="100" style=" color:#000; width: {{ projet.avancementMax // 1}}%;">
                      {{ projet.avancementMax // 1}}%
                      {#http://stackoverflow.com/questions/10682091/rounding-numbers-in-twig#}
                    </div>
                </div>

            </td>

        </tr>
    {% endfor %}
</table>
</tbody>
{% endblock %}